apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor
  template:
    metadata:
      labels:
        app: editor
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/clioude/editor
        name: editor
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: default.conf
            path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: editor
spec:
  ports:
  - port: 80
  selector:
    app: editor
  type: LoadBalancer
  externalTrafficPolicy: Local
