apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10-alpine
        name: postgres
        env:
        - name: POSTGRES_DB
          value: clioude
        - name: POSTGRES_PASSWORD
          value: clioude
        - name: POSTGRES_USER
          value: clioude
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: volume-pg
          subPath: postgres-data
      restartPolicy: Always
      volumes:
        - name: volume-pg
          persistentVolumeClaim:
            claimName: pg
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  clusterIP: None