apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/clioude/server
        name: server
        env:
        - name: DB_URL
          value: postgresql://clioude:clioude@postgres:5432/clioude
        - name: WORKER_TOKEN
          value: YOUR_TOKEN_HERE
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - port: 8080
  selector:
    app: server