"""init

Revision ID: 1c8e26c03625
Revises: 
Create Date: 2020-05-14 00:55:00.914868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8e26c03625'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('cpu_core', sa.Integer(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('service_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_hostname'), 'workers', ['hostname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_hostname'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
