name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          editor:
            - 'clioude-editor/**/*'
          server:
            - 'clioude-server/**/*'
          worker:
            - 'clioude-worker/**/*'
          lsphub:
            - 'clioude-lsphub/**/*'
          runenv:
            - 'clioude-runenv/**/*'
    - name: login
      run: docker login docker.io -u ${{ secrets.HUB_USER }} -p ${{ secrets.HUB_PSWD }} 
    - name: build editor
      if: steps.filter.outputs.editor == 'true'
      run: |
        docker build clioude-editor --tag ${{ secrets.HUB_USER }}/clioude-editor:latest
        docker push ${{ secrets.HUB_USER }}/clioude-editor:latest
    - name: build server
      if: steps.filter.outputs.server == 'true'
      run: |
        docker build clioude-server --tag ${{ secrets.HUB_USER }}/clioude-server:latest
        docker push ${{ secrets.HUB_USER }}/clioude-server:latest
    - name: build runenv
      if: steps.filter.outputs.runenv == 'true'
      run: |
        docker build clioude-runenv --tag ${{ secrets.HUB_USER }}/clioude-runenv:latest
        docker push ${{ secrets.HUB_USER }}/clioude-runenv:latest
    - name: build worker
      if: steps.filter.outputs.runenv == 'true' || steps.filter.outputs.worker == 'true'
      run: |
        docker build clioude-worker --tag ${{ secrets.HUB_USER }}/clioude-worker:latest
        docker push ${{ secrets.HUB_USER }}/clioude-worker:latest
    - name: build lsphub
      if: steps.filter.outputs.runenv == 'true' || steps.filter.outputs.lsphub == 'true'
      run: |
        docker build clioude-lsphub --tag ${{ secrets.HUB_USER }}/clioude-lsphub:latest
        docker push ${{ secrets.HUB_USER }}/clioude-lsphub:latest
