name: Docker Image Build & Publish

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          hub:
            - 'hub/**/*'
          runner:
            - 'runner/**/*'
    - name: login
      run: docker login docker.io -u ${{ secrets.HUB_USER }} -p ${{ secrets.HUB_PSWD }} 
    - name: build hub
      if: steps.filter.outputs.hub == 'true'
      run: |
        docker build hub --tag ${{ secrets.HUB_USER }}/clioude-hub:latest
        docker push ${{ secrets.HUB_USER }}/clioude-hub:latest
