name: Deploy & End to End Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Switch docker
      run: |
        minikube -p minikube docker-env | head -4 | awk '{gsub(/"/,""); print $2}' | while read -r line; do
          echo $line
          echo $line >> $GITHUB_ENV
        done
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          editor:
            - 'clioude-editor/**/*'
          server:
            - 'clioude-server/**/*'
          worker:
            - 'clioude-worker/**/*'
          lsphub:
            - 'clioude-lsphub/**/*'
    - name: build editor
      if: steps.filter.outputs.editor == 'true'
      run: docker build clioude-editor --tag ccw630/clioude-editor:latest
    - name: build server
      if: steps.filter.outputs.server == 'true'
      run: docker build clioude-server --tag ccw630/clioude-server:latest
    - name: build worker
      if: steps.filter.outputs.worker == 'true'
      run: docker build clioude-worker --tag ccw630/clioude-worker:latest
    - name: build lsphub
      if: steps.filter.outputs.lsphub == 'true'
      run: docker build clioude-lsphub --tag ccw630/clioude-lsphub:latest
    - name: Deploy
      run: kubectl apply -f clioude-deploy/
    - name: Before test
      run: kubectl wait --for=condition=Ready pods --all --timeout=300s && echo "CLIOUDE_URL=$(minikube service editor --url)" >> $GITHUB_ENV
    - name: Run tests
      uses: DevExpress/testcafe-action@latest
      with:
          args: "chrome:headless clioude-tester/test_cases --skip-js-errors"
