name: Deploy & End to End Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Switch docker
      run: minikube -p minikube docker-env | head -4 | awk '{gsub(/"/,""); print $2}' >> $GITHUB_ENV
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          hub:
            - 'hub/**/*'
          runner:
            - 'runner/**/*'
    - name: hub UT
      if: steps.filter.outputs.hub == 'true'
      run: cd hub && go test
    - name: runner UT
      if: steps.filter.outputs.runner == 'true'
      run: cd runner && cargo test

